### ISSUE TITLE
How to debug a failing test

### ISSUE THREAD

**Issue by jacargentina** [jasmine/gulp-jasmine-browser#14]
I'm getting some failing tests when using 0.1.2, with phantomjs; when running in the chrome browser i've no failures. I need to debug those failing tests to search for the problem.

My jasmine-console task is defined like this:

````
gulp.task('jasmine-console', function() {
  return gulp.src(testFiles)
    .pipe(jasmineBrowser.specRunner({
      console: true
    }))
    .pipe(jasmineBrowser.headless())
    .on('error', function(err) {
      console.log('ERROR: ', err);
    });
});
````

I've tried installing node-inspector npm package, and then going with:

    node-debug -p 8765 gulp jasmine-console

But breakpoints on my tests never stop. Any advice on how should i proceed?

**Comment by rdy** [comment]
Unfortunately, you won't be able to use a tool like node-debug because the console runner is executing in phantom (not quite a node environment), so debugging with node is impossible.

However, it would be possible to connect the chrome debugger to your phantomjs session, we don't have the option to do that yet but it would be pretty simple to add, then you would be able to put debugger lines in your test and have them show up in a remote chrome debugger window.

It would be along the lines of chrome debugging discussed in the remote debugging section in the phantomjs docs.
http://phantomjs.org/troubleshooting.html 

Would that be an acceptable workflow?

**Comment by jacargentina** [comment]
I've changed to using karma + chrome; hope some day this project can make easy to debug phantomjs
Cheers!
