### ISSUE TITLE
RequireJS supported?

### ISSUE THREAD

**Issue by leog** [jasmine/gulp-jasmine-browser#23]
Hello.

I come from Grunt where I used **grunt-contrib-jasmine** combined with **grunt-template-jasmine-requirejs**.

Is there any way I could use similar technique to load specs that use RequireJS?

Thanks a lot in advance.

**Comment by harryjoy** [comment]
+1.

I'm looking for the same.

**Comment by rdy** [comment]
It is quite possible that this would work fine combined with https://github.com/robinthrift/gulp-requirejs

Since I don't use require.js on any major project at the moment I can't test this. But I believe it might work in such a flow.

I'm not certain if the headless flow with phantomjs will work as well since the stream creates the test runner only after all files are added to the stream and it is completed. In the require.js I'm pretty sure there isn't a notion of "finished." The in browser flow should work with the continuous stream, that is how we recommend doing watch tasks with browserify or webpack flows.

If you have an simple example project somewhere I'd be glad to try it out and see.

**Comment by leog** [comment]
Actually @rdy, I think we are talking about different things. **gulp-requirejs** is all about optimization of the code whereas what we want to pursue is being able to have a RequireJS wrapper as **grunt-template-jasmine-requirejs** provides to be able to define a test like this:

```javascript
define([
    'angular-mocks',
    'filters/fileSize.flt'
], function () {
    describe('fileSize.flt', function() {
        var moFileSize;
        beforeEach(module('FileSizeFilter'));
        beforeEach(inject(function ($filter) {
            moFileSize = $filter('fileSizeFlt');
        }));
        describe('fileSizeFlt', function() {
            it('should convert bytes', function() {
                expect(moFileSize(1000)).toEqual('1000 b');
                expect(moFileSize(1020)).toEqual('1020 b');
            });
        });
    });
});
```

Extracted from the sample app I've written which uses **grunt-contrib-jasmine** combined with **grunt-template-jasmine-requirejs**.

**Comment by rdy** [comment]
I believe we could make that work, we would probably have to change how the jasmine runner works to make it run only after all modules are loaded from require.js. That should be the only change, it would probably need a custom runner. This isn't high on my list of priorites as I'd prefer to see something like systemJS or jspm instead of require.js. I'd be happy to take a pull request.
