### ISSUE TITLE
Defer scripts running until dom ready

### ISSUE THREAD

**Issue by MadMub** [jasmine/gulp-jasmine-browser#36]
Apologies if this is not the appropriate place to post this, was wondering if there is an option to defer my specs from running until the dom is ready? Perhaps I somehow specify the following callback? http://phantomjs.org/api/webpage/handler/on-load-finished.html

Any information is greatly appreciated, thank you for maintaining and supporting this tool.

EDIT: I was able to get my specs to pass by wrapping each files describe blocks in a small `ready()` wrapper, am still wondering though if via a flag the script tags can be attached to the body instead of the head?

**Comment by rdy** [comment]
I'm happy to move the spec runner to the official dom ready method which should work in phantom,  I might need to check to see if older phantom supports this method first.

**Comment by prantlf** [comment]
@MadMub, what is the error, that you're getting? You shouldn't need the requested change, although the change shouldn't break existing interface of this plugin.

`SpecRunner` doesn't execute the specs right away. The page, which it generates, loads `boot.js` from `jasmine-core`, which in turn executes `jasmine.getEnv()..execute()` in a `window.onload` callback.

If you enclose your code in `it`, `beforeAll` or `beforeEach` callbacks, your test code will run after the page was loaded. You cannot put your code to the root of a test module or to the `describe` callback,. because it would be evaluated during the module loading time;l not after the page got loaded.

**Comment by slackersoft** [comment]
Closing since gulp-jasmine-browser is discontinued
